<?php

namespace Kite\OhMyEmma\Interfaces;

use Test\Kite\OhMyEmma\RequestMock as RequestMock;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-20 at 20:39:25.
 */
class MembersTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Members
     */
    protected $members;
    protected $request;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->request = new RequestMock();
        $this->members = new Members($this->request);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kite\OhMyEmma\Interfaces\Members::getMembers
     * @todo   Implement testGetMembers().
     */
    public function testGetMembers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kite\OhMyEmma\Interfaces\Members::updateAddMember
     * @todo   Implement testUpdateAddMember().
     */
    public function testUpdateAddMember()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kite\OhMyEmma\Interfaces\Members::removeMember
     * @todo   Implement testRemoveMember().
     */
    public function testRemoveMember()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kite\OhMyEmma\Interfaces\Members::changeStatus
     * @todo   Implement testChangeStatus().
     */
    public function testChangeStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kite\OhMyEmma\Interfaces\Members::getGroups
     * @todo   Implement testGetGroups().
     */
    public function testGetGroups()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kite\OhMyEmma\Interfaces\Members::addRemoveGroupMembers
     * @todo   Implement testAddRemoveGroupMembers().
     */
    public function testAddRemoveGroupMembers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kite\OhMyEmma\Interfaces\Members::removeAllMembers
     * @todo   Implement testRemoveAllMembers().
     */
    public function testRemoveAllMembers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kite\OhMyEmma\Interfaces\Members::removeFromGroup
     * @todo   Implement testRemoveFromGroup().
     */
    public function testRemoveFromGroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kite\OhMyEmma\Interfaces\Members::getMemberMailingHistory
     * @todo   Implement testGetMemberMailingHistory().
     */
    public function testGetMemberMailingHistory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kite\OhMyEmma\Interfaces\Members::getImportInformation
     * @todo   Implement testGetImportInformation().
     */
    public function testGetImportInformation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kite\OhMyEmma\Interfaces\Members::deleteImport
     * @todo   Implement testDeleteImport().
     */
    public function testDeleteImport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kite\OhMyEmma\Interfaces\Members::groupStatuses
     * @todo   Implement testGroupStatuses().
     */
    public function testGroupStatuses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Kite\OhMyEmma\Interfaces\Members::convertStatus
     * @todo   Implement testConvertStatus().
     */
    public function testConvertStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
