<?php
namespace Kite\OhMyEmma;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-02 at 21:21:11.
 */
class EmmaTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Emma
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->emma = new Emma('','','','');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kite\OhMyEmma\Emma::__construct
     */
    public function testConstructWithNoInterface()
    {

        $emma = new Emma('','','','');

        $this->assertInstanceOf("Kite\OhMyEmma\Emma", $emma);
        $this->assertEmpty($emma->control);

    }

    /**
     * @covers Kite\OhMyEmma\Emma::__construct
     */
    public function testConstruct()
    {

        $emma = new Emma(
            '1111',
            '2222',
            '3333',
            'members'
        );

        $this->assertInstanceOf("Kite\OhMyEmma\Emma", $emma);
        $this->assertNotEmpty($emma->control);

    }

    /**
     * @covers Kite\OhMyEmma\Emma::build
     */
    public function testBuild()
    {
        $emma = new Emma(
            '1111',
            '2222',
            '3333',
            ''
        );

        $request = "holder";

        $this->assertEmpty($emma->control);
        $emma->build('members', $request);
        $this->assertInstanceOf("Kite\OhMyEmma\Members", $emma->control);

    }
}
