<?php
namespace Kite\OhMyEmma;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-02 at 21:21:11.
 */
class EmmaTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Emma
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->emma = new Emma('','','','');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Kite\OhMyEmma\Emma::__construct
     */
    public function testConstructWithNoInterface()
    {

        $emma = new Emma('','','','');

        $this->assertInstanceOf("Kite\OhMyEmma\Emma", $emma);
        $this->assertEmpty($emma->control);

    }

    /**
     * @covers Kite\OhMyEmma\Emma::__construct
     */
    public function testConstruct()
    {

        $emma = new Emma(
            '1111',
            '2222',
            '3333'
        );

        $this->assertInstanceOf("Kite\OhMyEmma\Emma", $emma);
        $this->assertNotEmpty($emma->Members);

    }

    /**
     * @covers Kite\OhMyEmma\Emma::__get
     */
    public function testGet()
    {
        $emma = new Emma(
            '1111',
            '2222',
            '3333'
        );

        $this->assertInstanceOf("Kite\OhMyEmma\Interfaces\Fields", $emma->Fields);
        $this->assertInstanceOf("Kite\OhMyEmma\Interfaces\Groups", $emma->Groups);
        $this->assertInstanceOf("Kite\OhMyEmma\Interfaces\Mailings", $emma->Mailings);
        $this->assertInstanceOf("Kite\OhMyEmma\Interfaces\Members", $emma->Members);
        $this->assertInstanceOf("Kite\OhMyEmma\Interfaces\Responses", $emma->Responses);
        $this->assertInstanceOf("Kite\OhMyEmma\Interfaces\Searches", $emma->Searches);
        $this->assertInstanceOf("Kite\OhMyEmma\Interfaces\Triggers", $emma->Triggers);
        $this->assertInstanceOf("Kite\OhMyEmma\Interfaces\Webhooks", $emma->Webhooks);
        
    }
}
